### ISSUE TITLE
Order status codes

### ISSUE THREAD

**Issue by aerth** [Selly/docs#1]
I think the order status codes are missing. 

Maybe the "here" word is supposed to be a link to their location in [_orders.md.html](https://github.com/Selly/docs/blob/f158d259d15f4a1d345468a4d2af3bd697de8116/source/includes/_orders.html.md).

All we have is "Status of the order. The status codes that are used can be found here"

**Comment by Sexual** [comment]
We've added this at https://developer.selly.gg/#order-statuses

Our documentation is a little lacklustre at the moment, it's missing a few resources and actions. Hopefully, we'll have the documentation caught up in the next few days.
